version: '3.4'

services:
  test:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/code
    entrypoint:
        - dotnet
        - test
        - /code/Business.UnitTests/Business.UnitTests.csproj