global using System.Collections.Generic;
global using Xunit;
global using FluentAssertions;
global using Common.Contract;
global using Common.String;
global using Common.Number;
global using AutoFixture;
global using AutoFixture.Kernel;
global using AutoFixture.AutoMoq;